In [2]:
function createGraphFromFile(filename)
	f = open(filename)
	lines = readlines(f)
	firstLine = split(lines[1])
	n = parse(Int64, firstLine[1]) #número de vértices
	g = parse(Int64, firstLine[2]) #número de grupos
	secondLine = split(lines[2])
    L = zeros(g) #limite inferior do grupo j
    U = zeros(g) #limite superior do grupo j
    for j=1:g
    	L[j] = parse(Float64, secondLine[j*2-1])
    	U[j] = parse(Float64, secondLine[j*2])
    end
    p = zeros(n) #peso do vértice i
    thirdLine = split(lines[3])
    for i=1:n
    	p[i] = parse(Float64, thirdLine[i])
    end
    numberOfLines = size(lines)[1]
    A = zeros(n,n) #matriz de adjacência em que cada elemento representa o peso da aresta entre o vértice u e v
    for lineIndex=4:numberOfLines
    	currentLine = split(lines[lineIndex])
    	u = parse(Int64, currentLine[1]) + 1 #vértice de índice u aqui tem índice u-1 na instância
        v = parse(Int64, currentLine[2]) + 1
        A[u,v] = parse(Float64, currentLine[3])
    end
    return n, g, p, L, U, A
end

n, g, p, L, U, A = createGraphFromFile("D:/UFRGS/Quinto Semestre/Otimização Combinatória/Trabalho final/instanciaTeste.ins")

(4, 2, [1.0, 2.0, 3.0, 4.0], [1.0, 1.0], [10.0, 10.0], [0.0 2.0 0.0 0.0; 0.0 0.0 3.0 0.0; 0.0 0.0 0.0 4.0; 1.0 0.0 0.0 0.0])

In [3]:
using JuMP
using GLPKMathProgInterface
m = Model(solver=GLPKSolverMIP(msg_lev=GLPK.MSG_ALL, tm_lim=3600000, out_frq=1))

@variable(m, x[1:n, 1:g], Bin) #g é o número de grupos
@variable(m, c[1:n, 1:n, 1:g], Bin) #g é o número de grupos
@objective( m, Max, sum( c[i,k,j]*A[i,k] for i in 1:n for k in 1:n for j in 1:g ) )
@constraints(m, begin
[i in 1:n], sum(x[i,j] for j in 1:g)==1
[j in 1:g], L[j]<=sum( x[i,j]*p[i] for i in 1:n )<=U[j]
[i in 1:n, k in 1:n, j in 1:g], c[i,k,j]<=(x[i,j]+x[k,j])/2 # isso daqui garante que vou ter tanto c[1,2,j] quanto c[2,1,j], então não preciso me preocupar com qual vértice escolher pra i e qual pra k na função objetivo

end)
solve(m)

:Optimal

GLPK Integer Optimizer, v4.52
38 rows, 40 columns, 104 non-zeros
40 integer variables, all of which are binary
Integer optimization begins...
+    19: mip =     not found yet <=              +inf        (1; 0)
+    21: mip =     not found yet <=  1.000000000e+001        (2; 0)
+    24: mip =     not found yet <=  1.000000000e+001        (2; 0)
+    26: mip =     not found yet <=  1.000000000e+001        (3; 0)
+    29: >>>>>  5.000000000e+000 <=  1.000000000e+001 100.0% (3; 0)
+    29: mip =  5.000000000e+000 <=  1.000000000e+001 100.0% (2; 1)
+    32: mip =  5.000000000e+000 <=  1.000000000e+001 100.0% (3; 1)
+    34: mip =  5.000000000e+000 <=  1.000000000e+001 100.0% (4; 1)
+    38: mip =  5.000000000e+000 <=  9.000000000e+000  80.0% (5; 1)
+    42: mip =  5.000000000e+000 <=  9.000000000e+000  80.0% (6; 1)
+    44: mip =  5.000000000e+000 <=  9.000000000e+000  80.0% (7; 1)
+    44: mip =  5.000000000e+000 <=  9.000000000e+000  80.0% (6; 2)
+    46: mip =  5.000000000e+000 <=  9.000

In [4]:
getobjectivevalue(m)

7.0

In [5]:
getvalue(x)

4×2 Array{Float64,2}:
 0.0  1.0
 1.0  0.0
 1.0  0.0
 1.0  0.0

In [18]:
function createGraphFromFile(filename)
	f = open(filename)
	lines = readlines(f)
	firstLine = split(lines[1])
	n = parse(Int64, firstLine[1]) #número de vértices
	g = parse(Int64, firstLine[2]) #número de grupos
	secondLine = split(lines[2])
    L = zeros(g) #limite inferior do grupo j
    U = zeros(g) #limite superior do grupo j
    for j=1:g
    	L[j] = parse(Float64, secondLine[j*2-1])
    	U[j] = parse(Float64, secondLine[j*2])
    end
    p = zeros(n) #peso do vértice i
    thirdLine = split(lines[3])
    for i=1:n
    	p[i] = parse(Float64, thirdLine[i])
    end
    numberOfLines = size(lines)[1]
    A = zeros(n,n) #matriz de adjacência em que cada elemento representa o peso da aresta entre o vértice u e v
    for lineIndex=4:numberOfLines
    	currentLine = split(lines[lineIndex])
    	u = parse(Int64, currentLine[1]) + 1 #vértice de índice u aqui tem índice u-1 na instância
        v = parse(Int64, currentLine[2]) + 1
        A[u,v] = parse(Float64, currentLine[3])
    end
    return n, g, p, L, U, A
end

n, g, p, L, U, A = createGraphFromFile("D:/UFRGS/Quinto Semestre/Otimização Combinatória/Trabalho final/instanciaTeste2.ins")

(4, 2, [1.0, 2.0, 3.0, 4.0], [0.0, 0.0], [10.0, 10.0], [0.0 2.0 0.0 0.0; 0.0 0.0 3.0 0.0; 0.0 0.0 0.0 4.0; 1.0 0.0 0.0 0.0])

In [19]:
using JuMP
using GLPKMathProgInterface
m = Model(solver=GLPKSolverMIP(msg_lev=GLPK.MSG_ALL, tm_lim=3600000, out_frq=1))

@variable(m, x[1:n, 1:g], Bin) #g é o número de grupos
@variable(m, c[1:n, 1:n, 1:g], Bin) #g é o número de grupos
@objective( m, Max, sum( c[i,k,j]*A[i,k] for i in 1:n for k in 1:n for j in 1:g ) )
@constraints(m, begin
[i in 1:n], sum(x[i,j] for j in 1:g)==1
[j in 1:g], L[j]<=sum( x[i,j]*p[i] for i in 1:n )<=U[j]
[i in 1:n, k in 1:n, j in 1:g], c[i,k,j]<=(x[i,j]+x[k,j])/2 # isso daqui garante que vou ter tanto c[1,2,j] quanto c[2,1,j], então não preciso me preocupar com qual vértice escolher pra i e qual pra k na função objetivo

end)
solve(m)

:Optimal

GLPK Integer Optimizer, v4.52
38 rows, 40 columns, 104 non-zeros
40 integer variables, all of which are binary
Integer optimization begins...
+    20: mip =     not found yet <=              +inf        (1; 0)
+    20: >>>>>  1.000000000e+001 <=  1.000000000e+001   0.0% (1; 0)
+    20: mip =  1.000000000e+001 <=     tree is empty   0.0% (0; 1)
INTEGER OPTIMAL SOLUTION FOUND


In [20]:
getobjectivevalue(m)

10.0

In [22]:
getvalue(x)

4×2 Array{Float64,2}:
 0.0  1.0
 0.0  1.0
 0.0  1.0
 0.0  1.0

Notar que, como o peso mínimo de um grupo pode ser igual a 0, isso equivale a dizer que não precisamos ter vértice nenhum nele. Perguntar pro Ritt se isso faz sentido.

In [25]:
function createGraphFromFile(filename)
	f = open(filename)
	lines = readlines(f)
	firstLine = split(lines[1])
	n = parse(Int64, firstLine[1]) #número de vértices
	g = parse(Int64, firstLine[2]) #número de grupos
	secondLine = split(lines[2])
    L = zeros(g) #limite inferior do grupo j
    U = zeros(g) #limite superior do grupo j
    for j=1:g
    	L[j] = parse(Float64, secondLine[j*2-1])
    	U[j] = parse(Float64, secondLine[j*2])
    end
    p = zeros(n) #peso do vértice i
    thirdLine = split(lines[3])
    for i=1:n
    	p[i] = parse(Float64, thirdLine[i])
    end
    numberOfLines = size(lines)[1]
    A = zeros(n,n) #matriz de adjacência em que cada elemento representa o peso da aresta entre o vértice u e v
    for lineIndex=4:numberOfLines
    	currentLine = split(lines[lineIndex])
    	u = parse(Int64, currentLine[1]) + 1 #vértice de índice u aqui tem índice u-1 na instância
        v = parse(Int64, currentLine[2]) + 1
        A[u,v] = parse(Float64, currentLine[3])
    end
    return n, g, p, L, U, A
end

n, g, p, L, U, A = createGraphFromFile("D:/UFRGS/Quinto Semestre/Otimização Combinatória/Trabalho final/instanciaTeste3.ins")

(4, 2, [1.0, 2.0, 3.0, 4.0], [10.0, 1.0], [10.0, 10.0], [0.0 2.0 0.0 0.0; 0.0 0.0 3.0 0.0; 0.0 0.0 0.0 4.0; 1.0 0.0 0.0 0.0])

In [26]:
using JuMP
using GLPKMathProgInterface
m = Model(solver=GLPKSolverMIP(msg_lev=GLPK.MSG_ALL, tm_lim=3600000, out_frq=1))

@variable(m, x[1:n, 1:g], Bin) #g é o número de grupos
@variable(m, c[1:n, 1:n, 1:g], Bin) #g é o número de grupos
@objective( m, Max, sum( c[i,k,j]*A[i,k] for i in 1:n for k in 1:n for j in 1:g ) )
@constraints(m, begin
[i in 1:n], sum(x[i,j] for j in 1:g)==1
[j in 1:g], L[j]<=sum( x[i,j]*p[i] for i in 1:n )<=U[j]
[i in 1:n, k in 1:n, j in 1:g], c[i,k,j]<=(x[i,j]+x[k,j])/2 # isso daqui garante que vou ter tanto c[1,2,j] quanto c[2,1,j], então não preciso me preocupar com qual vértice escolher pra i e qual pra k na função objetivo

end)
solve(m)

GLPK Integer Optimizer, v4.52
38 rows, 40 columns, 104 non-zeros
40 integer variables, all of which are binary
glp_intopt: optimal basis to initial LP relaxation not provided


:Infeasible

In [27]:
getobjectivevalue(m)

NaN

In [28]:
getvalue(x)

4×2 Array{Float64,2}:
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN

Problema infactível. Queremos que um grupo tenha peso igual a 10, e outro com peso igual a 1. Contudo, o peso total dos vértices é 10.

In [33]:
function createGraphFromFile(filename)
	f = open(filename)
	lines = readlines(f)
	firstLine = split(lines[1])
	n = parse(Int64, firstLine[1]) #número de vértices
	g = parse(Int64, firstLine[2]) #número de grupos
	secondLine = split(lines[2])
    L = zeros(g) #limite inferior do grupo j
    U = zeros(g) #limite superior do grupo j
    for j=1:g
    	L[j] = parse(Float64, secondLine[j*2-1])
    	U[j] = parse(Float64, secondLine[j*2])
    end
    p = zeros(n) #peso do vértice i
    thirdLine = split(lines[3])
    for i=1:n
    	p[i] = parse(Float64, thirdLine[i])
    end
    numberOfLines = size(lines)[1]
    A = zeros(n,n) #matriz de adjacência em que cada elemento representa o peso da aresta entre o vértice u e v
    for lineIndex=4:numberOfLines
    	currentLine = split(lines[lineIndex])
    	u = parse(Int64, currentLine[1]) + 1 #vértice de índice u aqui tem índice u-1 na instância
        v = parse(Int64, currentLine[2]) + 1
        A[u,v] = parse(Float64, currentLine[3])
    end
    return n, g, p, L, U, A
end

n, g, p, L, U, A = createGraphFromFile("D:/UFRGS/Quinto Semestre/Otimização Combinatória/Trabalho final/instanciaTeste4.ins")

(4, 2, [1.0, 2.0, 3.0, 4.0], [1.0, 1.0], [10.0, 10.0], [0.0 15.0 0.0 0.0; 0.0 0.0 16.0 0.0; 0.0 0.0 0.0 17.0; 14.0 0.0 0.0 0.0])

In [34]:
using JuMP
using GLPKMathProgInterface
m = Model(solver=GLPKSolverMIP(msg_lev=GLPK.MSG_ALL, tm_lim=3600000, out_frq=1))

@variable(m, x[1:n, 1:g], Bin) #g é o número de grupos
@variable(m, c[1:n, 1:n, 1:g], Bin) #g é o número de grupos
@objective( m, Max, sum( c[i,k,j]*A[i,k] for i in 1:n for k in 1:n for j in 1:g ) )
@constraints(m, begin
[i in 1:n], sum(x[i,j] for j in 1:g)==1
[j in 1:g], L[j]<=sum( x[i,j]*p[i] for i in 1:n )<=U[j]
[i in 1:n, k in 1:n, j in 1:g], c[i,k,j]<=(x[i,j]+x[k,j])/2 # isso daqui garante que vou ter tanto c[1,2,j] quanto c[2,1,j], então não preciso me preocupar com qual vértice escolher pra i e qual pra k na função objetivo

end)
solve(m)

:Optimal

GLPK Integer Optimizer, v4.52
38 rows, 40 columns, 104 non-zeros
40 integer variables, all of which are binary
Integer optimization begins...
+    19: mip =     not found yet <=              +inf        (1; 0)
+    21: mip =     not found yet <=  6.200000000e+001        (2; 0)
+    27: mip =     not found yet <=  6.200000000e+001        (2; 0)
+    29: mip =     not found yet <=  6.200000000e+001        (3; 0)
+    32: >>>>>  2.900000000e+001 <=  6.200000000e+001 113.8% (3; 0)
+    32: mip =  2.900000000e+001 <=  6.200000000e+001 113.8% (2; 1)
+    36: mip =  2.900000000e+001 <=  6.200000000e+001 113.8% (3; 1)
+    38: mip =  2.900000000e+001 <=  6.200000000e+001 113.8% (4; 1)
+    43: mip =  2.900000000e+001 <=  6.200000000e+001 113.8% (5; 1)
+    45: mip =  2.900000000e+001 <=  6.200000000e+001 113.8% (5; 1)
+    46: mip =  2.900000000e+001 <=  6.200000000e+001 113.8% (6; 1)
+    48: >>>>>  3.300000000e+001 <=  6.200000000e+001  87.9% (6; 1)
+    48: mip =  3.300000000e+001 <=  6.200

In [35]:
getobjectivevalue(m)

33.0

In [36]:
getvalue(x)

4×2 Array{Float64,2}:
 1.0  0.0
 0.0  1.0
 0.0  1.0
 0.0  1.0

In [38]:
getvalue(sum( x[i,1]*p[i] for i in 1:n ))

1.0

Só o vértice 1 está no grupo j=1. Ele tem peso 1. Logo, peso do grupo é 1.

In [39]:
getvalue(sum( x[i,2]*p[i] for i in 1:n ))

9.0

Os vértices 2, 3 e 4 estão no grupo j=2. A soma de seus pesos é 9. Logo, o peso do grupo é 9.